---
document:
  name: "Piano triennale ICT"
  description: "Il Piano triennale Ã¨ costruito sulla base di un Modello strategico di evoluzione del sistema informativo della Pubblica amministrazione e indirizza il piano delle gare, il piano dei finanziamenti e i piani triennali delle singole PA."
  tags:
    - "piano triennale"
